# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'upload.ui'
#
# Created: Fri Oct 16 08:33:20 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1286, 850)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout_3 = QtGui.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.keyword_edit = QtGui.QLineEdit(self.groupBox)
        self.keyword_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.keyword_edit.setObjectName("keyword_edit")
        self.horizontalLayout_2.addWidget(self.keyword_edit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prodction_type = QtGui.QComboBox(self.groupBox)
        self.prodction_type.setObjectName("prodction_type")
        self.prodction_type.addItem("")
        self.prodction_type.addItem("")
        self.prodction_type.addItem("")
        self.prodction_type.addItem("")
        self.horizontalLayout.addWidget(self.prodction_type)
        self.app_store = QtGui.QComboBox(self.groupBox)
        self.app_store.setObjectName("app_store")
        self.app_store.addItem("")
        self.app_store.addItem("")
        self.app_store.addItem("")
        self.app_store.addItem("")
        self.app_store.addItem("")
        self.horizontalLayout.addWidget(self.app_store)
        self.studio = QtGui.QComboBox(self.groupBox)
        self.studio.setObjectName("studio")
        self.studio.addItem("")
        self.studio.addItem("")
        self.studio.addItem("")
        self.horizontalLayout.addWidget(self.studio)
        self.status = QtGui.QComboBox(self.groupBox)
        self.status.setObjectName("status")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.horizontalLayout.addWidget(self.status)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btn_get_meta = QtGui.QPushButton(Form)
        self.btn_get_meta.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_get_meta.setObjectName("btn_get_meta")
        self.horizontalLayout_3.addWidget(self.btn_get_meta)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem4, 0, 1, 1, 1)
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tableView = QtGui.QTableView(self.splitter)
        self.tableView.setObjectName("tableView")
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtGui.QTextBrowser(self.widget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.groupBox_2 = QtGui.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_upoad_meta = QtGui.QPushButton(self.groupBox_2)
        self.btn_upoad_meta.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_upoad_meta.setObjectName("btn_upoad_meta")
        self.gridLayout_2.addWidget(self.btn_upoad_meta, 0, 1, 1, 1)
        self.msg = QtGui.QLabel(self.groupBox_2)
        self.msg.setObjectName("msg")
        self.gridLayout_2.addWidget(self.msg, 0, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 7)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout_3.addWidget(self.splitter, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "filter", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "搜索关键字", None, QtGui.QApplication.UnicodeUTF8))
        self.prodction_type.setItemText(0, QtGui.QApplication.translate("Form", "Production Type", None, QtGui.QApplication.UnicodeUTF8))
        self.prodction_type.setItemText(1, QtGui.QApplication.translate("Form", "-------------------", None, QtGui.QApplication.UnicodeUTF8))
        self.prodction_type.setItemText(2, QtGui.QApplication.translate("Form", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.prodction_type.setItemText(3, QtGui.QApplication.translate("Form", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.app_store.setItemText(0, QtGui.QApplication.translate("Form", "App Store", None, QtGui.QApplication.UnicodeUTF8))
        self.app_store.setItemText(1, QtGui.QApplication.translate("Form", "---------------", None, QtGui.QApplication.UnicodeUTF8))
        self.app_store.setItemText(2, QtGui.QApplication.translate("Form", "iTunes Apple Store", None, QtGui.QApplication.UnicodeUTF8))
        self.app_store.setItemText(3, QtGui.QApplication.translate("Form", "Google Play", None, QtGui.QApplication.UnicodeUTF8))
        self.app_store.setItemText(4, QtGui.QApplication.translate("Form", "Amazon App Store", None, QtGui.QApplication.UnicodeUTF8))
        self.studio.setItemText(0, QtGui.QApplication.translate("Form", "Studio", None, QtGui.QApplication.UnicodeUTF8))
        self.studio.setItemText(1, QtGui.QApplication.translate("Form", "---------------", None, QtGui.QApplication.UnicodeUTF8))
        self.studio.setItemText(2, QtGui.QApplication.translate("Form", "新建项目", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setItemText(0, QtGui.QApplication.translate("Form", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setItemText(1, QtGui.QApplication.translate("Form", "------------------", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setItemText(2, QtGui.QApplication.translate("Form", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setItemText(3, QtGui.QApplication.translate("Form", "Procession", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setItemText(4, QtGui.QApplication.translate("Form", "Ready for approval", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_get_meta.setText(QtGui.QApplication.translate("Form", "获取", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", " ", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_upoad_meta.setText(QtGui.QApplication.translate("Form", "上传", None, QtGui.QApplication.UnicodeUTF8))
        self.msg.setText(QtGui.QApplication.translate("Form", "上传信息显示", None, QtGui.QApplication.UnicodeUTF8))

