# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'upload.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1286, 850)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.keyword_edit = QtWidgets.QLineEdit(Form)
        self.keyword_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.keyword_edit.setObjectName("keyword_edit")
        self.horizontalLayout.addWidget(self.keyword_edit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btn_get_meta = QtWidgets.QPushButton(Form)
        self.btn_get_meta.setObjectName("btn_get_meta")
        self.horizontalLayout.addWidget(self.btn_get_meta)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.btn_upoad_meta = QtWidgets.QPushButton(Form)
        self.btn_upoad_meta.setObjectName("btn_upoad_meta")
        self.horizontalLayout.addWidget(self.btn_upoad_meta)
        spacerItem4 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem5, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.prodction_type = QtWidgets.QComboBox(Form)
        self.prodction_type.setObjectName("prodction_type")
        self.prodction_type.addItem("")
        self.prodction_type.addItem("")
        self.prodction_type.addItem("")
        self.prodction_type.addItem("")
        self.horizontalLayout_2.addWidget(self.prodction_type)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.app_store = QtWidgets.QComboBox(Form)
        self.app_store.setObjectName("app_store")
        self.app_store.addItem("")
        self.app_store.addItem("")
        self.app_store.addItem("")
        self.app_store.addItem("")
        self.app_store.addItem("")
        self.horizontalLayout_2.addWidget(self.app_store)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.studio = QtWidgets.QComboBox(Form)
        self.studio.setObjectName("studio")
        self.studio.addItem("")
        self.studio.addItem("")
        self.studio.addItem("")
        self.horizontalLayout_2.addWidget(self.studio)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.status = QtWidgets.QComboBox(Form)
        self.status.setObjectName("status")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.horizontalLayout_2.addWidget(self.status)
        spacerItem10 = QtWidgets.QSpacerItem(508, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 3)
        spacerItem11 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem11, 4, 1, 1, 1)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tableView = QtWidgets.QTableView(self.splitter)
        self.tableView.setObjectName("tableView")
        self.textBrowser = QtWidgets.QTextBrowser(self.splitter)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.splitter, 5, 0, 1, 3)
        self.gridLayout.setRowStretch(5, 1)
        self.tableView.raise_()
        self.btn_get_meta.raise_()
        self.btn_upoad_meta.raise_()
        self.studio.raise_()
        self.app_store.raise_()
        self.prodction_type.raise_()
        self.keyword_edit.raise_()
        self.label.raise_()
        self.status.raise_()
        self.textBrowser.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "搜索关键字"))
        self.btn_get_meta.setText(_translate("Form", "获取"))
        self.btn_upoad_meta.setText(_translate("Form", "上传"))
        self.prodction_type.setItemText(0, _translate("Form", "Production Type"))
        self.prodction_type.setItemText(1, _translate("Form", "-------------------"))
        self.prodction_type.setItemText(2, _translate("Form", "New"))
        self.prodction_type.setItemText(3, _translate("Form", "Update"))
        self.app_store.setItemText(0, _translate("Form", "App Store"))
        self.app_store.setItemText(1, _translate("Form", "---------------"))
        self.app_store.setItemText(2, _translate("Form", "iTunes Apple Store"))
        self.app_store.setItemText(3, _translate("Form", "Google Play"))
        self.app_store.setItemText(4, _translate("Form", "Amazon App Store"))
        self.studio.setItemText(0, _translate("Form", "Studio"))
        self.studio.setItemText(1, _translate("Form", "---------------"))
        self.studio.setItemText(2, _translate("Form", "新建项目"))
        self.status.setItemText(0, _translate("Form", "Status"))
        self.status.setItemText(1, _translate("Form", "------------------"))
        self.status.setItemText(2, _translate("Form", "New"))
        self.status.setItemText(3, _translate("Form", "Procession"))
        self.status.setItemText(4, _translate("Form", "Ready for approval"))

